# Generated by Django 5.0.4 on 2024-04-13 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('map_location', models.URLField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3487844.11496039!2d32.44041769453558!3d31.383867609568092!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1500492432a7c98b%3A0x6a6b422013352cba!2sIsrael!5e0!3m2!1sen!2sil!4v1712740457423!5m2!1sen!2sil', max_length=1000)),
                ('contact_details', models.CharField(max_length=255)),
                ('available_spaces', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('review', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('identifier', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='identifier')),
                ('name', models.CharField(max_length=20, verbose_name="item's name")),
                ('field_1', models.CharField(max_length=80, verbose_name='field 1')),
                ('field_2', models.IntegerField(verbose_name='field 2')),
                ('field_3', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], help_text='User type selection (yes/no)', max_length=3, verbose_name='field 3')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('service_provider_notes', models.TextField(blank=True, null=True)),
                ('client_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Website.service')),
                ('service_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Website.serviceitem')),
            ],
        ),
    ]
