# Generated by Django 5.0.4 on 2024-04-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceitem',
            old_name='name',
            new_name='description',
        ),
    ]
