# Generated by Django 5.0.4 on 2024-04-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_rename_name_serviceitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='map_location',
        ),
    ]
