# Generated by Django 5.0.4 on 2024-04-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_alter_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.DateTimeField(default=None),
        ),
    ]
