# Generated by Django 5.0.4 on 2024-04-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0011_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(default='10:00:00'),
        ),
    ]
