# Generated by Django 5.0.4 on 2024-04-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_alter_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='close_time',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AddField(
            model_name='service',
            name='open_time',
            field=models.TimeField(default='10:00:00'),
        ),
    ]
