# Generated by Django 5.0.4 on 2024-04-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_service_close_time_service_open_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='close_time',
            new_name='closing_time',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='open_time',
            new_name='opening_time',
        ),
    ]
