# Generated by Django 5.0.4 on 2024-04-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0014_rename_close_time_service_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
